### ISSUE TITLE
With improvements?

### ISSUE THREAD

**Issue by karl-petter** [jefflab/GSMSHIELD#1]
Hi,

I just stumbled upon your repo for GSMSHIELD. I found another one here in GitHub that is based in the same source https://github.com/tomn46037/GSMSHIELD What I can see there are only one difference between yours and the one from tomm46037. He changed the pins to fit the SeeedStudio GSM Shield.

I'm about to to investigate some time to evaluate a good library for the SeeedStudio GSM Shield and wondered what improvements you have implemented compared with the original version? Preferably I would very much like to see one repo that we all can fork from and then create branches for specific modification like changing the pins for a specific hardware.

My plan is to find a very memory efficient solution since I want to be able to run the code on all Arduinos, even the ones with just 1K ram. So from that point of view it would be great to be able to start from a common repo and then make contributions to that, or keep own forks if those changes does not fit everyone. So interested in your view on the subject.

**Comment by jefflab** [comment]
Thanks for reaching out. We made a bunch of changes, but they didn't get uploaded here. I'll try to update this repo later today. I think it is a good idea to have a better library to share and improve.

**Comment by karl-petter** [comment]
Great! When I started using Arduinos and GSMShields about 3 years ago the only reasonable lib I found was this http://wiki.groundlab.cc/doku.php?id=gsm_arduino_library (now available at https://github.com/IEFRD/GSM-ARDUINO) but it used quite a lot of RAM so had quite a lot of problems but after about a year I had a version that worked well with the SIM900. So that is what we currently use in the wind stations I have developed, see http://www.blast.nu/products/. But was never really satisfied with the software design of it so always have had in mind to re-write it and finally got some time to do that. And so first thing was to start looking around what exists today and this library seems quite nice but I noticed it does not use PROGMEM for the AT and HTTP strings so still consumes quite a lot of RAM which I would like to change. And I have at least one other project that will use this as well. So now it makes sense to spend some effort on it.

Another thing I would like to do if possible is to make so it can be mutually used with the standard Ethernet libraries(https://github.com/arduino/Arduino/tree/master/libraries/Ethernet), more specifically the EthernetClient one since it does not really make sense to implement a GPRS based server. Then it would be easy to use all other libraries that are targeting the EthernetClient.

May I ask what your current use of the library is and what the plans for it are? One upcoming project that I'm involved in will use both units with GSMShields but also Wifi like in the Yun. Thus t would be very convenient to easily be able to just swap the underlying libraries while the applications are the same even if different hardware is used.

**Comment by jefflab** [comment]
I now realize that we're not using this library any more. It seems that the GBoard folks already refactored this code, fixed some bugs, and republished it on their GBoard Pro downloads page. We made a copy of the code and posted it here:

https://github.com/tuletech/gboard_gsm

We extended a few timeouts, but otherwise it is mostly unchanged.

We used this code for prototypes, but our production units will not be using the SIM900, so I'm not sure how much help we'll be able to provide you.

**Comment by karl-petter** [comment]
I'll look into the gboard code, maybe it has the design i'm lookibg for otherwise I'll cook my own. The main issue I have is that none of the GAM-GPRS libraries I have looked at has a class that inherits from Client which both exists in the libraries for WiFiShield and the Ethernet.

**Comment by jefflab** [comment]
When you open the gboard code, you'll notice it is basically the same code as this repo. Same method names, implementation, etc. The only difference is that they put everyone into 1 file and fixed a few bugs.

I look forward to seeing what you come up with. Hopefully we can use standard AT commands that support more than the SIM900. Let me know when you start coding your new library and I'd love to help if I can.

**Comment by karl-petter** [comment]
I have some spare time in-between phases of a project so I took use of the time and started. So have created a first sketch, mainly focusing on the classes and their relationships. It is all available here https://github.com/YellowOrb/GSMGPRS_Shield Do you want to be added as a collaborator there?

It's lunch time here right now so I will continue in the afternoon and add some more documentation to it. Try to structure my thoughts around it. And start adding issues as a start of a to-do list.
